import type { Metadata } from "next";
import { Inter, Poppins, Shantell_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-poppins',
  display: 'swap'
});

const shantellSans = Shantell_Sans({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: '--font-shantell-sans',
  display: 'swap'
});

const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`dark ${poppins.variable} ${shantellSans.variable} ${inter.variable}`}>
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center">
          <Navbar />
        </div>
        {children} 
      </body>
    </html>
  );
}